### ISSUE TITLE
Kill Value

### ISSUE THREAD

**Issue by Bengeljo** [hmes98318/r6-discord-bot#4]
Hey, 
I looked through your code and what you are grabbing from the side. I try to understand it but can't really since I don't know the method that you are using.
I changed the code so people can also look up different platforms and I noticed later that the general kill value is missing.
My knowledge about how to grab something from a website is like not there. Did you miss the value or can't you grab it ? 
My first try to have a kills value was to multiply the death count with the K/D, it kinda works but since both are different build, I only get NaN. (K/D decimal gets represented with a . and to show the thousand count we get a comma , and I think there we get the NaN.

Would love to see if you find a way to grab the kill count. 

Best regards 
Bengeljo

**Comment by Bengeljo** [comment]
[bot.zip](https://github.com/hmes98318/r6-discord-bot/files/7779984/bot.zip)
here is the code for the different platforms. Now you have to write +r6 [platform] [name]
It also works when you ad operator [op_name] or rank/casual so all functions are still there
Hope you can get the kill value

**Comment by hmes98318** [comment]
> Hey, I looked through your code and what you are grabbing from the side. I try to understand it but can't really since I don't know the method that you are using. I changed the code so people can also look up different platforms and I noticed later that the general kill value is missing. My knowledge about how to grab something from a website is like not there. Did you miss the value or can't you grab it ? My first try to have a kills value was to multiply the death count with the K/D, it kinda works but since both are different build, I only get NaN. (K/D decimal gets represented with a . and to show the thousand count we get a comma , and I think there we get the NaN.
> 
> Would love to see if you find a way to grab the kill count.
> 
> Best regards Bengeljo

Hi Bengeljo,
Thank you for discovering the error I wrote, I have corrected it and uploaded it (v1.2.2) again
At the beginning, I also encountered the problem of decimal point and thousand count comma
I tried to use [FilterArray()](https://github.com/hmes98318/r6-discord-bot/blob/077b5f0a2765ffa2bffffbaf4aca6a7ca46982bf/r6/r6.js#L173) to rearrange this array
In this [position,](https://github.com/hmes98318/r6-discord-bot/blob/077b5f0a2765ffa2bffffbaf4aca6a7ca46982bf/r6_request.js#L69) you can see what it does

Maybe it can help your problem

Looking forward to your reply
hmes98318

**Comment by hmes98318** [comment]
> 

Thanks for your advice
I have added it to the code

**Comment by hmes98318** [comment]
> [bot.zip](https://github.com/hmes98318/r6-discord-bot/files/7779984/bot.zip) here is the code for the different platforms. Now you have to write +r6 [platform] [name] It also works when you ad operator [op_name] or rank/casual so all functions are still there Hope you can get the kill value

Thanks for your advice
I have added it to the code

**Comment by Bengeljo** [comment]
> > Hey, I looked through your code and what you are grabbing from the side. I try to understand it but can't really since I don't know the method that you are using. I changed the code so people can also look up different platforms and I noticed later that the general kill value is missing. My knowledge about how to grab something from a website is like not there. Did you miss the value or can't you grab it ? My first try to have a kills value was to multiply the death count with the K/D, it kinda works but since both are different build, I only get NaN. (K/D decimal gets represented with a . and to show the thousand count we get a comma , and I think there we get the NaN.
> > Would love to see if you find a way to grab the kill count.
> > Best regards Bengeljo
> 
> Hi Bengeljo, Thank you for discovering the error I wrote, I have corrected it and uploaded it (v1.2.2) again At the beginning, I also encountered the problem of decimal point and thousand count comma I tried to use [FilterArray()](https://github.com/hmes98318/r6-discord-bot/blob/077b5f0a2765ffa2bffffbaf4aca6a7ca46982bf/r6/r6.js#L173) to rearrange this array In this [position,](https://github.com/hmes98318/r6-discord-bot/blob/077b5f0a2765ffa2bffffbaf4aca6a7ca46982bf/r6_request.js#L69) you can see what it does
> 
> Maybe it can help your problem
> 
> Looking forward to your reply hmes98318

Hey, thanks for adding my changes into your code.
But that was kinda not the reason I wrote. 
I wrote since when you request the general stats, under the K/D value  you get to Death: Value and I miss there the kill value. 
The thing is in r6_record there is also no GENERAL_kill so you miss to grab the value from the side or you just can't. It just don't know. ^^" 

 I tired to understand what you were doing with the Filterarray but I still pretty new to programming in general so, at this point I can't help you but maybe in a month. I try to programm everyday for at least an hour. 
Hope  I can help you in the future

Looking forward to your reply and maybe updates Bengeljo

**Comment by hmes98318** [comment]
> Hey, thanks for adding my changes into your code. But that was kinda not the reason I wrote. I wrote since when you request the general stats, under the K/D value you get to Death: Value and I miss there the kill value. The thing is in r6_record there is also no GENERAL_kill so you miss to grab the value from the side or you just can't. It just don't know. ^^"
> 
> I tired to understand what you were doing with the Filterarray but I still pretty new to programming in general so, at this point I can't help you but maybe in a month. I try to programm everyday for at least an hour. Hope I can help you in the future
> 
> Looking forward to your reply and maybe updates Bengeljo

Hi Bengeljo,
I understand the question you asked.
I forgot to add [GENER_KILL](https://github.com/hmes98318/r6-discord-bot/commit/dfd1a2d742f015265433f3a97771ba423bcd074b) count when I started coding this project.
I haven't noticed this. I have corrected it and uploaded it ([v1.2.3](https://github.com/hmes98318/r6-discord-bot/releases/tag/1.2.3)) again.
I appreciate your advice.

Thank you and maybe you can come to my house having some Netflix and chill  : )

Best Regards
hmes98318

**Comment by Bengeljo** [comment]
Well I got it even running on slash commands now on Discord.V13. It was hard but a cool journey
